class Rokok{
	public static void main(String[] args) {
		int RokokSurya,RokokJuara,RokokCamel,RokokSampoerna,JumlahBelanja,JumlahTotalBelanja;
		//harga masing-masing rokok//
		RokokSurya = 30000;
		RokokJuara = 15000;
		RokokCamel = 15000;
		RokokSampoerna = 28000;
		
		//total masing-masing harga//
		var totalRokokSurya = RokokSurya * 10;
		var totalRokokJuara = RokokJuara * 11;
		var totalRokokCamel = RokokCamel * 9;
		var totalRokokSampoerna = RokokSampoerna * 15;
		var jumlahtotalbelanja = totalRokokSurya + totalRokokJuara + totalRokokCamel + totalRokokSampoerna;
		
		//perhitungan jumlah masing-masing barang yang di belanjakan/
		System.out.println("Total Rokok Surya= " + totalRokokSurya);
		System.out.println("Total Rokok Juara= " + totalRokokJuara);
		System.out.println("Total Rokok Camel= " + totalRokokCamel);
		System.out.println("Total Rokok Sampoerna= " + totalRokokSampoerna);
		System.out.println("Jumlah Total Belanja= " + jumlahtotalbelanja);
		System.out.println("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
		System.out.println(" (! !) ");
		System.out.println(" ('.')");
		System.out.println(" ( > IRPAN  ");
	}
}